### ISSUE TITLE
Unable to open mail account

### ISSUE THREAD

**Issue by barok1383** [owncloudarchive/mail#1652]
### Steps to reproduce
I don't know ... yesterday everything was fine, today I got an error. Didn't touch anything between yesterday and today. After the error, I update mail app from 0.53 to 0.6, same error.
Looks like this : https://github.com/owncloudarchive/mail/issues/1307 but I don't have any javascript error.

### Expected behaviour
The mail account should open

### Actual behaviour
Message "We couldn’t load Boîte de réception :-\" with an error 500

### Mail app

**Mail app version:**
0.6

**Mailserver or service:**
My own mail server. I have 3 accounts, 2 are functionals, there is only one that I can't open

**Transport security - IMAP:**
SSL

**Transport security - SMTP:** 
SSL

**Number of accounts:**
3, only 1 with problem

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**:
Ubuntu server 16.04 LTS

**Web server:**
Apache 2.4

**Database:**
MariaDB 10.0.27

**PHP version:**

**Version:** (see admin page)
7.08

**Updated from an older version or fresh install:**
Updated with the distribution upgrade in september, no error since yesterday

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - contacts: 1.4.0.0
  - dav: 0.2.6
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - mail: 0.6.0
  - notifications: 0.3.0
  - passwords: 19
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**

<details>
{
    "system": {
        "instanceid": "ocad0s91u60e",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.yakoupi.com",
            "yakoupi.com"
        ],
        "datadirectory": "\/home\/www\/owncloud_data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.1.1.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false
    }
}

</details>

#### Client configuration
Opera 40.0.2308.81 but same error with Edge, Chrome

**Operating system:**
Windows 7 64-bit (WoW64)
##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/owncloud.log or data/nextcloud.log)
<details>
Exception: {"Exception":"TypeError","Message":"Argument 1 passed to OCA\\Mail\\Model\\IMAPMessage::hordeToAssoc() must be an instance of Horde_Mail_Rfc822_Address, instance of Horde_Mail_Rfc822_Group given, called in \/var\/www\/owncloud\/apps\/mail\/lib\/model\/convertaddresses.php on line 74","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/mail\/lib\/model\/convertaddresses.php(74): OCA\\Mail\\Model\\IMAPMessage->hordeToAssoc(Object(Horde_Mail_Rfc822_Group))\n#1 \/var\/www\/owncloud\/apps\/mail\/lib\/model\/imapmessage.php(216): OCA\\Mail\\Model\\IMAPMessage->convertAddressList(Object(Horde_Mail_Rfc822_List))\n#2 \/var\/www\/owncloud\/apps\/mail\/lib\/model\/imapmessage.php(485): OCA\\Mail\\Model\\IMAPMessage->getToList(true)\n#3 \/var\/www\/owncloud\/apps\/mail\/lib\/mailbox.php(190): OCA\\Mail\\Model\\IMAPMessage->getListArray()\n#4 \/var\/www\/owncloud\/apps\/mail\/lib\/controller\/messagescontroller.php(137): OCA\\Mail\\Mailbox->getMessages(0, 21, '')\n#5 [internal function]: OCA\\Mail\\Controller\\MessagesController->index(4, 'SU5CT1g=', 0, 20, '', NULL)\n#6 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Mail\\Controller\\MessagesController), 'index')\n#8 \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Mail\\Controller\\MessagesController), 'index')\n#9 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('OCA\\\\Mail\\\\Contro...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#11 \/var\/www\/owncloud\/lib\/private\/Route\/Router.php(280): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#12 \/var\/www\/owncloud\/lib\/base.php(891): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#13 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/owncloud\/apps\/mail\/lib\/model\/convertaddresses.php","Line":34}
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
Seems to be a PHP error, this log isn't necessary
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
Seems to be a PHP error, this log isn't necessary</details>

##### Browser log
<details>
a) https://..../index.php/apps/mail/accounts/4/folders/SU5CT1g%3D/messages?filter= 500 (Internal Server Error)
</details>

************************************************************************
Feel free to contact me if you want more information.

Regards

**Comment by RealRancor** [comment]
https://github.com/owncloudarchive/mail#this-repo-is-no-longer-maintained-we-moved-the-development-of-this-app-to-nextcloud-instead
